# Aula 1 - An√°lise de Dados com Pandas

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [13]:
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [15]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [16]:
df.shape

(133349, 11)

In [17]:
linhas, colunas = df.shape[0], df.shape[1]
print("linhas:",linhas,"colunas:",colunas)

linhas: 133349 colunas: 11

In [18]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [19]:
df.rename(columns={
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}, inplace=True)

df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [20]:
df['senioridade'].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [21]:
df['contrato'].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [22]:
df['remoto'].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [23]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [24]:
senioridade = {'SE':'Senior', 'MI':'Pleno', 'EN':'Junior', 'EX': 'Executivo'}
df['senioridade'] = df['senioridade'].replace(senioridade)
df['senioridade'].value_counts()

senioridade
Senior       77241
Pleno        40465
Junior       12443
Executivo     3200
Name: count, dtype: int64

In [25]:
contrato = {'FT': 'Integral', 'PT': 'Parcial', 'CT': 'Contrato', 'FL': 'Freelance'}
df['contrato'] = df['contrato'].replace(contrato)
df['contrato'].value_counts()

contrato
Integral     132563
Contrato        394
Parcial         376
Freelance        16
Name: count, dtype: int64

In [26]:
tamanho_empresa = {'L': 'Grande', 'S': 'Pequena', 'M':'M√©dia'}
df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)
df['tamanho_empresa'].value_counts()

tamanho_empresa
M√©dia      129561
Grande       3574
Pequena       214
Name: count, dtype: int64

In [27]:
mapa_trabalho = {0: 'Presencial', 100: 'Remoto', 50: 'hibrido'}
df['remoto'] = df['remoto'].replace(mapa_trabalho)
df['remoto'].value_counts()

remoto
Presencial    105312
Remoto         27718
hibrido          319
Name: count, dtype: int64

In [28]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dia
1,2025.0,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dia
2,2025.0,Pleno,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dia
3,2025.0,Pleno,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dia
4,2025.0,Junior,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dia

In [29]:
df.describe(include='object')

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Integral,Data Scientist,USD,US,Presencial,US,M√©dia
freq,77241,132563,17314,126140,119579,105312,119641,129561

# Aula 2 - Prepara√ß√£o e limpeza dos Dados

In [8]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [30]:
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [31]:
df['ano'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [32]:
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,Senior,Integral,Product Manager,184500,USD,184500,US,Presencial,US,M√©dia
59692,NaN,Pleno,Integral,Engineer,110000,USD,110000,DE,Presencial,DE,M√©dia
59710,NaN,Junior,Integral,Data Scientist,208800,USD,208800,US,Presencial,US,M√©dia
59759,NaN,Senior,Integral,Software Engineer,135000,USD,135000,US,Presencial,US,M√©dia
59789,NaN,Senior,Integral,Engineer,112000,USD,112000,US,Presencial,US,M√©dia
131000,NaN,Senior,Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,M√©dia
131006,NaN,Senior,Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,M√©dia
133054,NaN,Junior,Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,Grande
133281,NaN,Pleno,Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,Grande
133317,NaN,Pleno,Integral,Data Scientist,130000,USD,130000,US,hibrido,US,Grande

In [41]:
import numpy as np
df_salarios = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', "Daniele", 'Val'],
    'salario': [4000, np.nan, 5000, np.nan, 100000]
})

df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())
df_salarios.head()

      nome   salario  salario_media  salario_mediana
0      Ana    4000.0        4000.00           4000.0
1    Bruno       NaN       36333.33           5000.0
2   Carlos    5000.0        5000.00           5000.0
3  Daniele       NaN       36333.33           5000.0
4      Val  100000.0      100000.00         100000.0

In [44]:
df_temperaturas = pd.DataFrame({
    'Dia': ['Segunda', 'Ter√ßa', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas['preenchido_ffill'] = df_temperaturas['Temperatura'].ffill()
df_temperaturas['preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

       Dia  Temperatura  preenchido_ffill  preenchido_bfill
0  Segunda         30.0              30.0              30.0
1    Ter√ßa          NaN              30.0              28.0
2   Quarta          NaN              30.0              28.0
3   Quinta         28.0              28.0              28.0
4    Sexta         27.0              27.0              27.0

In [46]:
df_cidades = pd.DataFrame({
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Daniele', 'Val'],
    'Cidade': ['S√£o Paulo', np.nan, 'Curitiba', np.nan, 'Bel√©n']
})

df_cidades['cidade_preenchida'] = df_cidades['Cidade'].fillna('N√£o informado')
df_cidades

      Nome     Cidade cidade_preenchida
0      Ana  S√£o Paulo         S√£o Paulo
1    Bruno        NaN     N√£o informado
2   Carlos   Curitiba          Curitiba
3  Daniele        NaN     N√£o informado
4      Val      Bel√©n             Bel√©n

In [47]:
df_limpo = df.dropna()

In [48]:
df_limpo.isnull().sum()

ano                0
senioridade        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
dtype: int64

In [49]:
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dia
1,2025.0,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dia
2,2025.0,Pleno,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dia
3,2025.0,Pleno,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dia
4,2025.0,Junior,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dia

In [52]:
df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dia
1,2025,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dia
2,2025,Pleno,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dia
3,2025,Pleno,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dia
4,2025,Junior,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dia